import React from 'react'

const GlobalContext = React.createContext({
  productVersionsData: [],
  setProductVersionsData: () => {},
  productVersionExploded: [],
  setProductVersionExploded: () => {},
  SBOMLinksData: [],
  setSBOMLinksData: () => {},
  vulnerabilitiesData: [],
  setVulnerabilitiesData: () => {},
  activitiesData: [],
  setActivitiesData: () => {},
  customerView: '',
  setCustomerView: () => {},
  minimize: false,
  setMinimize: () => {},
  activeDockerHub: true,
  setActiveDockerHub: () => {},
  userLocation: null,
  setUserLocation: () => {},
  selectedRows: [],
  setSelectedRows: () => {},
  registryList: [],
  setRegistryList: () => {},
  images: [],
  setImages: () => {},
  componentsVal: '',
  setComponentsVal: () => {},
  VulnerabilitiesVal: '',
  setVulnerabilitiesVal: () => {},
  activeVulnVal: '',
  setActiveVulnVal: () => {},
  riskScoreVal: '',
  setRiskScoreVal: () => {},
  scannerItems: [],
  SetScannerItems: () => {},
  isAuthenticate: false,
  setIsAuthenticate: () => {},
  scanEnabled: false,
  setScanEnabled: () => {},
  advisoriesData: [],
  setAdvisoriesData: () => {}
})

export default GlobalContext
