name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set a Node.js version here

    - name: Install Dependencies
      run: npm install  # You can change this to "npm install" if "npm ci" doesn't work

    - name: Build
      run: npm run build  # Build your project

    - name: Deploy to AWS S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
        path: ./build/*  # Path to your build directory
      env:
        AWS_S3_BUCKET: arn:aws:s3:::lynk-dash-app
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
